import { AppState } from './types';

export const initialData: AppState = {
  settings: {
    ecole_nom: 'ISB-COSERCO',
    slogan_ecole: "Former des ministres solides pour l'Eglise et la Nation",
    adresse_ecole: 'Brazzaville, Republique du Congo',
    telephone_ecole: '+242 06 000 00 00',
    email_ecole: 'contact@isb-coserco.cg',
    logo_path: null,
    fee_due_day: 5,
    receipt_logo_path: null,
    receipt_stamp_path: null,
    watermark_enabled: true,
    watermark_opacity: 0.08,
    watermark_scale: 0.5,
    background_image_path: null,
    background_opacity: 0.08,
    auto_backup_enabled: true,
    auto_backup_interval_minutes: 30,
    school_year_override: null,
  },
  classes: [
    { id: 'A1A', nom: '1ere Annee - Groupe A', grade: 'Groupe A', niveau: '1ere Annee', enseignant_principal: 'Pasteur Moukoko', frais_scolarite: 25000 },
    { id: 'A1B', nom: '1ere Annee - Groupe B', grade: 'Groupe B', niveau: '1ere Annee', enseignant_principal: 'Pasteur Moukoko', frais_scolarite: 25000 },
    { id: 'A2A', nom: '2eme Annee - Groupe A', grade: 'Groupe A', niveau: '2eme Annee', enseignant_principal: 'Dr. Banzouzi', frais_scolarite: 30000 },
    { id: 'A2B', nom: '2eme Annee - Groupe B', grade: 'Groupe B', niveau: '2eme Annee', enseignant_principal: 'Dr. Banzouzi', frais_scolarite: 30000 },
    { id: 'A3P', nom: '3eme Annee - Pastorale', grade: 'Section Pastorale', specialisation: 'Pastorale', niveau: '3eme Annee', enseignant_principal: 'Dr. Ngoma', frais_scolarite: 35000 },
    { id: 'A3M', nom: '3eme Annee - Missions', grade: 'Section Missionnaire', specialisation: 'Missions', niveau: '3eme Annee', enseignant_principal: 'Dr. Ngoma', frais_scolarite: 35000 },
  ],
  students: [
    { id: 'S2508010001', nom: 'MASSAMBA', prenom: 'Samuel', genre: 'Masculin', date_naissance: '1995-06-12', lieu_naissance: 'Brazzaville', adresse: 'Bacongo, Brazzaville', eglise_locale: 'Eglise du Reveil Bethesda', pasteur_recommandant: 'Pasteur Jean Okemba', telephone: '068799791', email: 'samuel.massamba@gmail.com', classe: '1ere Annee - Groupe A', annee_etude: '1ere Annee', niveau_admission: 'Baccalaureat', date_bapteme: '2012-08-15', statut_frais: 'En retard' },
    { id: 'S2508010002', nom: 'MOUANDA', prenom: 'Ruth', genre: 'Féminin', date_naissance: '1998-01-22', lieu_naissance: 'Pointe-Noire', adresse: 'Moungali, Brazzaville', eglise_locale: 'Assemblee de Dieu Sion', pasteur_recommandant: 'Pasteur Pierre Ndolo', telephone: '061234567', email: 'ruth.mouanda@gmail.com', classe: '2eme Annee - Groupe A', annee_etude: '2eme Annee', niveau_admission: 'Baccalaureat', date_bapteme: '2015-03-20', statut_frais: 'En retard' },
    { id: 'S2508010003', nom: 'NZONZI', prenom: 'David', genre: 'Masculin', date_naissance: '1992-11-05', lieu_naissance: 'Dolisie', adresse: 'Ouenze, Brazzaville', eglise_locale: 'Eglise Evangelique du Congo', pasteur_recommandant: 'Pasteur Andre Makaya', telephone: '067654321', email: 'david.nzonzi@gmail.com', classe: '3eme Annee - Pastorale', annee_etude: '3eme Annee', niveau_admission: 'BEPC', date_bapteme: '2010-12-25', statut_frais: 'En retard' },
  ],
  teachers: [
    { id: 'T2508010001', nom: 'Moukoko', prenom: 'Emmanuel', matiere: 'Introduction a la Bible et hermeneutique', niveaux_enseignes: ['1ere Annee'], embauche: '2024-10-01', telephone: '051234567', email: 'moukoko@isb-coserco.cg', salaire_mensuel: 300000 },
    { id: 'T2508010002', nom: 'Banzouzi', prenom: 'Aristide', matiere: 'Theologie Systematique', niveaux_enseignes: ['1ere Annee', '2eme Annee'], embauche: '2024-10-01', telephone: '069876543', email: 'banzouzi@isb-coserco.cg', salaire_mensuel: 350000 },
    { id: 'T2508010003', nom: 'Ngoma', prenom: 'Patience', matiere: 'Homiletique et Predication', niveaux_enseignes: ['2eme Annee', '3eme Annee'], embauche: '2024-10-01', telephone: '061122334', email: 'ngoma@isb-coserco.cg', salaire_mensuel: 320000 },
    { id: 'T2508010004', nom: 'Mpassi', prenom: 'Jeremie', matiere: 'Pneumatologie et Vie spirituelle', niveaux_enseignes: ['1ere Annee', '2eme Annee'], embauche: '2024-10-01', telephone: '065566778', email: 'mpassi@isb-coserco.cg', salaire_mensuel: 280000 },
    { id: 'T2508010005', nom: 'Kimbembe', prenom: 'Grace', matiere: 'Missiologie et Missions transculturelles', niveaux_enseignes: ['3eme Annee'], embauche: '2024-10-01', telephone: '069988776', email: 'kimbembe@isb-coserco.cg', salaire_mensuel: 300000 },
    { id: 'T2508010006', nom: 'Obambi', prenom: 'Rachel', matiere: 'Pastorale pratique et Counseling', niveaux_enseignes: ['2eme Annee', '3eme Annee'], embauche: '2024-10-01', telephone: '061239876', email: 'obambi@isb-coserco.cg', salaire_mensuel: 310000 },
    { id: 'T2508010007', nom: 'Loufoundou', prenom: 'Daniel', matiere: 'Leadership chretien et Direction', niveaux_enseignes: ['2eme Annee', '3eme Annee'], embauche: '2024-10-01', telephone: '064561237', email: 'loufoundou@isb-coserco.cg', salaire_mensuel: 290000 },
  ],
  staff: [
    { id: 'STF001', nom: 'OKEMBA', prenom: 'Nathalie', role: 'Secretaire Academique', embauche: '2024-10-01', telephone: '065551122', email: 'secretariat@isb-coserco.cg', salaire_mensuel: 180000 },
    { id: 'STF002', nom: 'MAKOSSO', prenom: 'Joseph', role: 'Directeur Spirituel', embauche: '2024-10-01', telephone: '067778899', email: 'spirituel@isb-coserco.cg', salaire_mensuel: 250000 },
    { id: 'STF003', nom: 'TSIBA', prenom: 'Merveille', role: 'Comptable', embauche: '2024-10-01', telephone: '066443322', email: 'comptabilite@isb-coserco.cg', salaire_mensuel: 200000 },
  ],
  expenses: [
    { id: 'EXP2', date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0], description: 'Achat de Bibles et manuels theologiques', category: 'Fournitures', amount: 150000 },
    { id: 'EXP3', date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0], description: 'Facture SNDE', category: 'Eau', amount: 35000 },
    { id: 'EXP4', date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0], description: 'Facture E2C', category: 'Électricité', amount: 65000 },
    { id: 'EXP5', date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0], description: 'Impression des syllabi et guides d\'etude', category: 'Impression', amount: 120000 },
  ],
  payments: [
    { id: 'PAY1', student_id: 'S2508010001', month: '2024-10', amount: 25000, date: '2024-10-04', method: 'Espèces', note: 'Paiement pour la rentree academique', receipt_no: 1, school_year: '2024-2025' },
    { id: 'PAY2', student_id: 'S2508010001', month: '2024-11', amount: 25000, date: '2024-11-02', method: 'Mobile Money', note: '', receipt_no: 2, school_year: '2024-2025' },
    { id: 'PAY3', student_id: 'S2508010002', month: '2024-10', amount: 30000, date: '2024-10-05', method: 'Virement', note: '', receipt_no: 3, school_year: '2024-2025' },
  ],
  salaryPayments: [],
  timetable: [
    { id: 'TT1', day: 'Lundi', time_start: '08:00', time_end: '10:00', subject: 'Introduction a la Bible', class_name: '1ere Annee - Groupe A', teacher_id: 'T2508010001' },
    { id: 'TT2', day: 'Lundi', time_start: '10:00', time_end: '12:00', subject: 'Theologie Systematique', class_name: '1ere Annee - Groupe A', teacher_id: 'T2508010002' },
    { id: 'TT3', day: 'Mardi', time_start: '08:00', time_end: '10:00', subject: 'Homiletique', class_name: '2eme Annee - Groupe A', teacher_id: 'T2508010003' },
  ],
  users: [
    { id: 'USR001', username: 'admin', password_hash: 'admin', prenom: 'Admin', nom: 'Recteur', role: 'Admin' },
  ],
  currentUser: null,
  next_sid: 4,
  next_tid: 8,
  next_staff_id: 4,
  next_cid: 7,
  next_expense_id: 6,
  next_payment_id: 4,
  next_salary_payment_id: 1,
  next_timetable_id: 4,
  next_receipt_no: 4,
  next_user_id: 2,
};
